import {
  ArrowCircleUpOutlineIcon,
  ArrowheadUpOutlineIcon,
  ArrowUpIcon,
  ArrowUpCircleIcon,
  ArrowUpCircleFillIcon,
  ArrowUpCircleLineIcon,
  ArrowUpFillIcon,
  ArrowUpLineIcon,
  ArrowUpOutlineIcon,
  ArrowUpsFillIcon,
  ArrowUpsLineIcon,
  // ArrowUpwardOutlineIcon,
  IconChevronCircleUp,
  LinkIcon,
  LinksLineIcon,
  ShareLineIcon,
  UploadOutlineIcon,
} from "../icons";

export const MATERIAL_ICONS: any = {
  IconChevronCircleUp,
  ArrowCircleUpOutlineIcon,
  ArrowheadUpOutlineIcon,
  ArrowUpIcon,
  ArrowUpCircleIcon,
  ArrowUpCircleFillIcon,
  ArrowUpCircleLineIcon,
  ArrowUpFillIcon,
  ArrowUpLineIcon,
  ArrowUpOutlineIcon,
  ArrowUpsFillIcon,
  ArrowUpsLineIcon,
  // ArrowUpwardOutlineIcon,
  // ChevronUpOutlineIcon,
  LinkIcon,
  LinksLineIcon,
  ShareLineIcon,
  UploadOutlineIcon,
};
